spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: org.h2.Driver
    url:  jdbc:h2:file:${user.home}/.tarzan-nav/db/tarzan-nav;MODE=MYSQL
    username: root
    password: 123456
  mail:
    host: smtp.163.com
    username: vxhqqh@163.com
    password: TRXZYKQFHNZHOYMB
    default-encoding: UTF-8
    protocol: smtp
    properties:
      mail:
        smtp:
           auth: true # 启用SMTP认证
           starttls:
              enabled: true # 启用SMTP认证
              required: true # 必须采用加密链接
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
tarzan:
  shiro-key: ${user.home}/.tarzan-nav/shiro_key.pub
  backup-dir: ${user.home}/.tarzan-nav/backup
  preview-enabled: false
social:
  enabled: true
  domain: http://127.0.0.1
  oauth:
    QQ:
      client-id: xxx
      client-secret: xxx
      redirect-uri: http://127.0.0.1:8443/oauth/gitee/callback
    WECHAT_OPEN:
      client-id: xxxxxx
      client-secret: xxxxxx
      redirect-uri: http://127.0.0.1:8443/oauth/baidu/callback
    GITEE:
      client-id: 5b693811f8229e38146f2c482e3f4e4dfbdf2b496d494698b6308d6f35dcb2e0
      client-secret: 428ff220b5aa5704c55a8cf91f13aa4466258a6e7c357c7e30a5bca1d1cbe4e2
      redirect-uri: http://127.0.0.1/auth/oauth/callback/GITEE
ai:
  maxNum:
    basic: 5 # 默认兜底策略
    wechat: 10 # 公众号用户
    star: 100 # 星球用户
    starTry: 30 # 星球用户
    invited: 0.1 # 被邀请
    inviteNum: 0.2 # 邀请人数执行策略
    starNumber: 4000 # 目前为 4000
  source: # 支持的AI模型
    - CHAT_GPT_3_5
    - CHAT_GPT_4
    - TARZAN_AI
    - XUN_FEI_AI
# chatgpt
chatgpt:
  main: CHAT_GPT_3_5
  conf:
    CHAT_GPT_3_5:
      keys:
        - # 这里输入你的key
      proxy: true # 表示走上面的代理进行访问
      apiHost: https://api.openai.com/
      timeOut: 900
      maxToken: 3000
    CHAT_GPT_4:
      keys:
        -
      proxy: true
      apiHost: https://api.openai.com/
      timeOut: 900
      maxToken: 200000
  number:
    # 普通用户
    normal: 50
    vip: 100
# 讯飞AI
xunfei:
  hostUrl: https://spark-api.xf-yun.com/v3.5/chat
  domain: "generalv3.5"
  appId: 5cf48f5c
  apiKey: b52cb7b745c2e8d6ca28e89470c5f378
  apiSecret: 60da6df9693e5b8af6bd32f77c4df3c3
tongyi:
  apiKey: sk-80611638022146a2bc9a1ec9b566cc54