spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: org.h2.Driver
    url:  jdbc:h2:file:${user.home}/.tarzan-navigation/db/navigation;MODE=MYSQL
    username: root
    password: 123456
  h2:
    console:
      enabled: false
      settings:
        web-allow-others: true
      path: /h2-console
  #jpa:
   #show-sql: true
   #hibernate:
     #ddl-auto: update
   #generate-ddl: false
server:
  servlet:
    context-path: /

file:
  #上传的文件对外暴露的访问路径
  access-path-pattern: /u/**
  #文件上传目录
  upload-folder: /file/upload/
  #文件预览、下载的访问路径前缀
  access-prefix-url: http://localhost:80/u

static:
  #静态html对外访问路径
  access-path-pattern: /html/**
  #静态html路径
  folder: /tarzanCms/html/path

tarzan:
  shiro-key: ${user.home}/.tarzan-navigation/shiro_key.pub
  backup-dir: ${user.home}/.tarzan-navigation/backup
  preview-enabled: false

social:
  enabled: true
  domain: http://127.0.0.1
  oauth:
    QQ:
      client-id: xxx
      client-secret: xxx
      redirect-uri: http://127.0.0.1:8443/oauth/gitee/callback
    WECHAT_OPEN:
      client-id: xxxxxx
      client-secret: xxxxxx
      redirect-uri: http://127.0.0.1:8443/oauth/baidu/callback
    GITEE:
      client-id: 5b693811f8229e38146f2c482e3f4e4dfbdf2b496d494698b6308d6f35dcb2e0
      client-secret: 428ff220b5aa5704c55a8cf91f13aa4466258a6e7c357c7e30a5bca1d1cbe4e2
      redirect-uri: http://127.0.0.1/auth/oauth/callback/GITEE

