spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: org.h2.Driver
    url:  jdbc:h2:file:${user.home}/.tarzan-nav/db/tarzan-nav;MODE=MYSQL
    username: root
    password: 123456
  mail:
    host: smtp.163.com
    username: vxhqqh@163.com
    password: TRXZYKQFHNZHOYMB
    default-encoding: UTF-8
    protocol: smtp
    properties:
      mail:
        smtp:
           auth: true # 启用SMTP认证
           starttls:
              enabled: true # 启用SMTP认证
              required: true # 必须采用加密链接
  h2:
    console:
      enabled: false
      settings:
        web-allow-others: false
      path: /h2-console
tarzan:
  shiro-key: ${user.home}/.tarzan-nav/shiro_key.pub
  backup-dir: ${user.home}/.tarzan-nav/backup
  preview-enabled: false
social:
  enabled: true
  domain: http://127.0.0.1
  oauth:
    QQ:
      client-id: xxx
      client-secret: xxx
      redirect-uri: http://127.0.0.1:8443/oauth/gitee/callback
    WECHAT_OPEN:
      client-id: xxxxxx
      client-secret: xxxxxx
      redirect-uri: http://127.0.0.1:8443/oauth/baidu/callback
    GITEE:
      client-id: 5b693811f8229e38146f2c482e3f4e4dfbdf2b496d494698b6308d6f35dcb2e0
      client-secret: 428ff220b5aa5704c55a8cf91f13aa4466258a6e7c357c7e30a5bca1d1cbe4e2
      redirect-uri: http://127.0.0.1/auth/oauth/callback/GITEE

csdn:
  cookies:

# 讯飞AI
xunfei:
  hostUrl: https://spark-api.xf-yun.com/v3.5/chat
  domain: "generalv3.5"
  appId:
  apiKey:
  apiSecret:
  day-limit: 10
# 文心ai
wenxin:
  apiKey:
  apiSecret:
  baseUrl: https://aip.baidubce.com
  chatUrl: /rpc/2.0/ai_custom/v1/wenxinworkshop/chat
  yi_34b_chat:
    day-limit: 15
  llama:
    day-limit: 5
#通义千问
tongyi:
  apiKey:
  day-limit: 10
linkai:
  signInUrl:
  accessToken:
  apiCode:
  apiKey:
  baseUrl: https://api.link-ai.chat
  chatUrl: /v1/chat/completions
  gpt4:
   day-limit: 1
  wenxin4:
    day-limit: 1