spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: org.h2.Driver
    url:  jdbc:h2:file:${user.home}/.tarzan-cms/db/cms;MODE=MYSQL
    username: root
    password: 123456
  h2:
    console:
      enabled: false
      settings:
        web-allow-others: false
      path: /h2-console
  mail:
    host: smtp.163.com
    username:
    password:
    default-encoding: UTF-8
    protocol: smtp
    properties:
      smtp:
        auth: true
        starttls:
          enable: true
          required: true
tarzan:
  shiro-key: ${user.home}/.tarzan-nav/shiro_key.pub
  backup-dir: ${user.home}/.tarzan-nav/backup
  preview-enabled: false
social:
  enabled: true
  domain: http://127.0.0.1
  oauth:
    QQ:
      client-id: xxx
      client-secret: xxx
      redirect-uri: http://127.0.0.1:8443/oauth/gitee/callback
    WECHAT_OPEN:
      client-id: xxxxxx
      client-secret: xxxxxx
      redirect-uri: http://127.0.0.1:8443/oauth/baidu/callback
    GITEE:
      client-id: 5b693811f8229e38146f2c482e3f4e4dfbdf2b496d494698b6308d6f35dcb2e0
      client-secret: 428ff220b5aa5704c55a8cf91f13aa4466258a6e7c357c7e30a5bca1d1cbe4e2
      redirect-uri: http://127.0.0.1/auth/oauth/callback/GITEE

